/* chapbook — the C ABI.
 *
 * GENERATED by cbindgen from crates/chapbook-ffi. Do not edit by hand:
 * `tests/header.rs` regenerates this and fails if it differs. Change the
 * Rust, then run `UPDATE_FFI_HEADER=1 cargo test -p chapbook-ffi`.
 *
 * Contract tier — see docs/STABILITY.md. Status codes and struct layouts
 * here are permanent; the strings behind cb_last_error_message are not. */

#ifndef CHAPBOOK_H
#define CHAPBOOK_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * What every fallible entry point returns. Zero is success; every failure
 * is negative, so `if (rc < 0)` is the whole host-side test.
 *
 * The numbers are deliberate and permanent. New conditions take new
 * numbers; none is ever reused for a different meaning, and none is
 * renumbered. Grouped so the ranges mean something: `-1..-9` are faults in
 * the *call itself*, which a correct host never sees, and `-10` down are
 * conditions from the engine, which it must handle.
 */
enum cb_status
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    CB_OK = 0,
    /**
     * A panic was caught at the boundary. One code, not a family: a panic
     * here is a chapbook bug, not a condition worth enumerating. The
     * message names the payload where it could be recovered.
     */
    CB_ERR_PANIC = -1,
    /**
     * A pointer argument that may not be null was null.
     */
    CB_ERR_NULL_ARGUMENT = -2,
    /**
     * A `const char*` was not valid UTF-8, or had no terminator in range.
     */
    CB_ERR_INVALID_UTF8 = -3,
    /**
     * The output buffer was too small. `*needed` holds the byte count that
     * would have sufficed, including the NUL.
     */
    CB_ERR_BUFFER_TOO_SMALL = -4,
    /**
     * An argument was well-formed but not usable: an out-of-range enum, a
     * zero-sized surface, a negative descriptor.
     */
    CB_ERR_INVALID_ARGUMENT = -5,
    /**
     * The call does not apply right now — asking a session with no metrics
     * for its render size, or for a page it has not laid out.
     */
    CB_ERR_UNAVAILABLE = -6,
    CB_ERR_BOOK_OPEN = -10,
    CB_ERR_BOOK_MALFORMED = -11,
    CB_ERR_RESOURCE_NOT_FOUND = -12,
    CB_ERR_FIXED_LAYOUT_UNSUPPORTED = -13,
    /**
     * The format is one chapbook implements and this build left out. A
     * distinct code because it is a packaging mistake, not a bad book, and
     * a host that reports it as corruption sends the reader hunting for a
     * problem in their file.
     */
    CB_ERR_FORMAT_NOT_BUILT = -14,
    CB_ERR_SPINE_OUT_OF_RANGE = -15,
    CB_ERR_PARSE = -16,
    CB_ERR_STYLE = -17,
    CB_ERR_LAYOUT = -18,
    CB_ERR_FONT = -19,
    CB_ERR_CFI = -20,
    CB_ERR_NETWORK = -21,
    CB_ERR_OPDS = -22,
    CB_ERR_LIBRARY = -23,
    CB_ERR_CREDENTIAL = -24,
    CB_ERR_PANEL = -25,
    CB_ERR_IO = -26,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum cb_status cb_status;
#else
typedef int32_t cb_status;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Which physical edge reading starts from. The book declares it — EPUB's
 * `page-progression-direction` — and the engine consults it; it crosses
 * the boundary so a host can *show* it, which is the only way a reader
 * can tell a correctly-flipped RTL book from a bug, and so a host's own
 * gestures (a page-turn swipe, say) can agree with the tap zones.
 */
enum cb_reading_direction
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * Left to right: the previous page is off the left edge.
     */
    CB_DIRECTION_LTR = 0,
    /**
     * Right to left: the previous page is off the right edge.
     */
    CB_DIRECTION_RTL = 1,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum cb_reading_direction cb_reading_direction;
#else
typedef uint32_t cb_reading_direction;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * A reader intent. Hosts produce these — from a tap zone, a key lookup,
 * or their own UI — and hand them to [`cb_session_apply`]; a host never
 * needs to interpret one.
 *
 * `CB_ACTION_NONE` is not an action: it is the "nothing" value
 * [`cb_session_tap_action`] and the key lookups answer with, and
 * [`cb_session_set_tap_zones`] accepts for a band that does nothing.
 * Applying it is an error, not a no-op.
 *
 * The set is open — bookmarks, search, a jump to the table of contents
 * are plainly coming — and new values are only ever appended. Values in
 * this header are permanent, so a host may persist them.
 */
enum cb_action
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    CB_ACTION_NONE = 0,
    /**
     * Forward one page in reading order.
     */
    CB_ACTION_NEXT_PAGE = 1,
    /**
     * Back one page in reading order.
     */
    CB_ACTION_PREV_PAGE = 2,
    /**
     * Forward one spine unit (chapter), landing on its first page.
     */
    CB_ACTION_NEXT_UNIT = 3,
    /**
     * Back one spine unit.
     */
    CB_ACTION_PREV_UNIT = 4,
    /**
     * Return to where a followed link was taken from.
     */
    CB_ACTION_BACK = 5,
    /**
     * Raise the base font size one step. The step is the engine's, so a
     * reader who changes device finds the same ladder.
     */
    CB_ACTION_FONT_UP = 6,
    /**
     * Lower the base font size one step.
     */
    CB_ACTION_FONT_DOWN = 7,
    /**
     * Advance the color theme one place in its cycle.
     */
    CB_ACTION_CYCLE_THEME = 8,
    /**
     * Show or hide the host's own chrome. The engine has no menu, so
     * applying this always comes back `CB_OUTCOME_UNHANDLED`: it exists
     * because *the middle of the page opens the menu* is the same policy
     * decision as *the outer thirds turn pages*.
     */
    CB_ACTION_TOGGLE_MENU = 9,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum cb_action cb_action;
#else
typedef uint32_t cb_action;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * A key, in the vocabulary the engine binds — not a platform keycode.
 *
 * A host translates its own stable codes into this: Android's
 * `KEYCODE_*`, the HID usages iOS and macOS report on hardware
 * keyboards, GDK keyvals. The translation has no opinions in it; the
 * opinions are in the table behind [`cb_key_default_action`]. Printable
 * characters are not here — they go through [`cb_char_default_action`].
 *
 * Modifiers are deliberately absent: chorded shortcuts are where a
 * host's own commands live, and an engine that claimed `Ctrl` would
 * collide with every one of them. Consult the table for unmodified
 * presses only.
 *
 * Zero is deliberately unassigned, so a zeroed variable never names a
 * key. The set is open, like [`cb_action`], and grows the same way.
 */
enum cb_key
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    CB_KEY_ARROW_LEFT = 1,
    CB_KEY_ARROW_RIGHT = 2,
    CB_KEY_ARROW_UP = 3,
    CB_KEY_ARROW_DOWN = 4,
    CB_KEY_PAGE_UP = 5,
    CB_KEY_PAGE_DOWN = 6,
    CB_KEY_SPACE = 7,
    CB_KEY_BACKSPACE = 8,
    /**
     * A dedicated previous-page button. Kobo and PocketBook put two on
     * the bezel; they arrive as `KEY_PAGEUP`, `KEY_PREV` or a function
     * key depending on the model and the kernel, which is exactly the
     * reverse-engineering a host should not have to repeat.
     */
    CB_KEY_TURN_PREV = 9,
    /**
     * A dedicated next-page button.
     */
    CB_KEY_TURN_NEXT = 10,
    /**
     * Volume up, which Android readers conventionally borrow for page
     * turns. Only forward it here if the host has already decided to
     * take it from the system — and note that iOS offers no way to.
     */
    CB_KEY_VOLUME_UP = 11,
    /**
     * Volume down.
     */
    CB_KEY_VOLUME_DOWN = 12,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum cb_key cb_key;
#else
typedef uint32_t cb_key;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * What the engine did with an action — two answers, because a host needs
 * both and can derive neither from the other: *should I repaint*, and
 * *did the reader consume this event*.
 *
 * The second answer is what a host owes its platform. Android's
 * `onKeyDown` must return `true` on `CHANGED` **and** `UNCHANGED`, or the
 * last page of every book gets the system volume slider drawn over it;
 * iOS's responder chain is the same shape — call `super` only on
 * `UNHANDLED`. `UNHANDLED` is also what `CB_ACTION_BACK` returns at the
 * bottom of the back trail, deliberately: that is exactly where the
 * platform's own Back should take over, so a host forwards the gesture
 * unconditionally instead of shadowing the history to know when to stop.
 *
 * Unlike [`cb_action`] this set is closed: consumed and repainting are
 * two bits, and the fourth corner — declining an event while demanding a
 * repaint — describes nothing.
 */
enum cb_action_outcome
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * Applied, and the position, size or theme moved. Consume the event
     * and repaint.
     */
    CB_OUTCOME_CHANGED = 0,
    /**
     * Applied, and nothing moved — the last page, or the font at its
     * stop. Consume the event anyway; do not repaint.
     */
    CB_OUTCOME_UNCHANGED = 1,
    /**
     * Not the engine's. Let the event through to the platform.
     */
    CB_OUTCOME_UNHANDLED = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum cb_action_outcome cb_action_outcome;
#else
typedef uint32_t cb_action_outcome;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Severity, matching `log`'s own ordering so the numbers are not a second
 * thing to remember.
 *
 * As chapbook uses them: `ERROR` is something the reader asked for that
 * did not happen, or state that was lost. `WARN` is degraded but nothing
 * lost. `INFO` is worth knowing and not a problem. Nothing is logged per
 * frame or per page turn — a session at rest is silent.
 */
enum cb_log_level
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    CB_LOG_OFF = 0,
    CB_LOG_ERROR = 1,
    CB_LOG_WARN = 2,
    CB_LOG_INFO = 3,
    CB_LOG_DEBUG = 4,
    CB_LOG_TRACE = 5,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum cb_log_level cb_log_level;
#else
typedef int32_t cb_log_level;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Which reader opens the bytes. `CB_FORMAT_GUESS` decides from the bytes
 * themselves, and is the right answer even when a name is available — the
 * EPUB `mimetype` entry and the `%PDF` header do not lie and an extension
 * does.
 */
enum cb_format
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    CB_FORMAT_GUESS = 0,
    CB_FORMAT_EPUB = 1,
    CB_FORMAT_CBZ = 2,
    CB_FORMAT_PDF = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum cb_format cb_format;
#else
typedef uint32_t cb_format;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Quarter-turns clockwise between the page as laid out and the panel it is
 * painted into. A property of the output, not the layout.
 */
enum cb_rotation
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    CB_ROTATION_NONE = 0,
    CB_ROTATION_QUARTER = 1,
    CB_ROTATION_HALF = 2,
    CB_ROTATION_THREE_QUARTER = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum cb_rotation cb_rotation;
#else
typedef uint32_t cb_rotation;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * What kind of book is open. Comics and PDFs page as images, which is why
 * a host may want to know before offering text-shaped affordances.
 */
enum cb_book_kind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    CB_BOOK_EPUB = 0,
    CB_BOOK_COMIC = 1,
    CB_BOOK_PDF = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum cb_book_kind cb_book_kind;
#else
typedef uint32_t cb_book_kind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Page ground and default text colours.
 */
enum cb_theme
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    CB_THEME_LIGHT = 0,
    CB_THEME_SEPIA = 1,
    CB_THEME_DARK = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum cb_theme cb_theme;
#else
typedef uint32_t cb_theme;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Where a settings change sticks.
 */
enum cb_settings_scope
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * Every book without an override of its own.
     */
    CB_SCOPE_GLOBAL = 0,
    /**
     * This book only.
     */
    CB_SCOPE_THIS_BOOK = 1,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum cb_settings_scope cb_settings_scope;
#else
typedef uint32_t cb_settings_scope;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Which optional capabilities this build actually has.
 *
 * A header cannot tell a host which `.so` it loaded, and the Android spike
 * is the argument: it built without the `library` feature for weeks, read
 * books perfectly, and silently remembered nothing — no error, because
 * there is nothing to error about. A build that can be configured down
 * must be able to say what it was configured to.
 */
enum cb_capability
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * Reading positions, annotations and settings persist. Without it a
     * session reads and remembers nothing.
     */
    CB_CAP_LIBRARY = 1,
    /**
     * CBZ comic archives open.
     */
    CB_CAP_CBZ = 2,
    /**
     * PDFs open.
     */
    CB_CAP_PDF = 4,
    /**
     * OPDS catalogs and streamed comics open.
     */
    CB_CAP_OPDS = 8,
    /**
     * A transport is bundled. Without it a host must supply its own before
     * anything can be fetched.
     */
    CB_CAP_BUNDLED_HTTP = 16,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum cb_capability cb_capability;
#else
typedef uint32_t cb_capability;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * A session configuration under construction. Opaque.
 */
typedef struct cb_config cb_config;

/**
 * A font source under construction. Opaque: its shape is Rust's.
 */
typedef struct cb_font_source cb_font_source;

/**
 * An open book. Opaque.
 */
typedef struct cb_session cb_session;

/**
 * Receives one diagnostic.
 *
 * `target` is the crate that emitted it — `chapbook_reader`,
 * `chapbook_library` — so a host can route or filter by subsystem. Both
 * strings are NUL-terminated, valid only for the duration of the call, and
 * must be copied if kept.
 *
 * **It may fire on any thread**, including the loader thread the host has
 * never seen. It must not call back into this ABI, and on a platform where
 * logging touches UI it must hand the message to whatever the main loop
 * watches rather than doing the work inline.
 */
typedef void (*cb_log_fn)(cb_log_level level, const char *target, const char *message, void *user);

/**
 * The page box, in logical units, plus the scale that turns it into
 * device pixels. Laying out at logical size and rasterizing at device
 * size is what keeps text a readable size on a dense panel.
 *
 * **`width` and `height` are the page in *reading* orientation, not the
 * panel you paint into.** They are the same thing only while `rotation`
 * is `CB_ROTATION_NONE`. On a quarter or three-quarter turn the axes
 * swap, so a host with a 600x800 view that wants a turned page passes
 * 800x600 here and gets 600x800 back from `cb_session_render_size`.
 *
 * Passing the view's own dimensions on a turn is not an error and will
 * not be reported as one: the page simply paginates to the wrong aspect,
 * and because you allocate from `cb_session_render_size` there is no
 * mismatch left for anything to catch. Rotation is a property of the
 * output; it must never change what the text reflows to.
 */
typedef struct cb_metrics {
    float width;
    float height;
    float margin_top;
    float margin_right;
    float margin_bottom;
    float margin_left;
    float dpi_scale;
    cb_rotation rotation;
} cb_metrics;

/**
 * Where the reader is.
 *
 * The pair, always. A page number alone is meaningless across a unit
 * boundary, and a host that stores one and compares it after a turn has a
 * bug the conformance harness exists to catch.
 */
typedef struct cb_position {
    uint32_t spine;
    uint32_t page;
} cb_position;

/**
 * How a page is typeset. `base_font_px` and `line_height` are the two a
 * reader adjusts; the rest a shell usually sets once.
 */
typedef struct cb_settings {
    float base_font_px;
    /**
     * Unitless multiplier.
     */
    float line_height;
    bool justify;
    /**
     * Honour the publisher's stylesheets. Off leaves UA and user sheets.
     */
    bool publisher_styles;
    cb_theme theme;
} cb_settings;

/**
 * Called when a background load finishes and there is something new to
 * show. **Fires on the loader thread**, not the host's UI thread: it must
 * only hand a token to whatever the host's main loop watches — a pipe, a
 * run-loop source, `Handler.post`. Attaching a JVM thread or touching UI
 * from inside it is the shape this comment exists to prevent.
 */
typedef void (*cb_wake_fn)(void *user);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * The version of this ABI, as `major * 10000 + minor * 100 + patch`.
 *
 * A host that loads the library at runtime — which is every Android app —
 * cannot tell from a header which build it actually got. This is how it
 * asks. Tracks the workspace version.
 */
uint32_t cb_abi_version(void);

/**
 * A bitmask of [`cb_capability`].
 */
uint32_t cb_capabilities(void);

/**
 * The host's installed fonts, its idea of the generics, its fallback list.
 *
 * Right for a desktop shell and wrong everywhere else: it produces **no
 * faces at all** on Android, iOS and wasm, where `cb_session_open_*` then
 * fails with `CB_ERR_FONT` rather than paginating every book to one blank
 * page. That failure is the feature.
 */
struct cb_font_source *cb_font_source_host(void);

/**
 * Exactly the fonts in `dir`, every generic pointed at `family`, no
 * fallback, a fixed locale. All three axes pinned, which is what makes
 * output comparable across machines — what a test corpus or a golden
 * wants, and what a shell shipping its own faces wants.
 */
struct cb_font_source *cb_font_source_embedded(const char *dir, const char *family);

/**
 * Android's system fonts: `/system/fonts`, the families Android actually
 * ships, and Noto for fallback.
 *
 * Present on every platform rather than behind a `cfg` so that the header
 * is the same file everywhere — a host that calls it off Android gets a
 * source that resolves to nothing and an honest `CB_ERR_FONT` at open.
 */
struct cb_font_source *cb_font_source_android_system(void);

/**
 * Add a directory of faces, searched recursively. Later sources add to
 * earlier ones, so this composes with the presets above.
 */
cb_status cb_font_source_add_dir(struct cb_font_source *fonts, const char *dir);

/**
 * Spell out all five CSS generic families.
 *
 * There is no partial form on purpose. Every platform's built-in answer is
 * wrong somewhere and wrong silently — fontdb's defaults are Microsoft
 * family names no phone has — so this ABI makes a host that touches the
 * generics at all name every one of them.
 */
cb_status cb_font_source_set_generics(struct cb_font_source *fonts,
                                      const char *serif,
                                      const char *sans_serif,
                                      const char *monospace,
                                      const char *cursive,
                                      const char *fantasy);

/**
 * Release a font source that was never handed to [`cb_config_new`].
 *
 * Passing null is a no-op, so a host can free unconditionally on an error
 * path without testing first.
 */
void cb_font_source_free(struct cb_font_source *fonts);

/**
 * Begin a configuration. **Consumes `fonts`**, whether or not it succeeds:
 * the handle is dead on return and must not be freed by the caller.
 */
struct cb_config *cb_config_new(struct cb_font_source *fonts);

/**
 * Where the library, its managed book copies and its covers live.
 *
 * Unset, the session asks the platform's convention, which exists on
 * desktops and nowhere else. A sandboxed app knows its own answer and
 * nothing else can: `context.getFilesDir()`, `Library/Application
 * Support`. Without a library a session still reads — it just remembers
 * nothing, and says nothing about it.
 */
cb_status cb_config_set_library_dir(struct cb_config *config, const char *dir);

/**
 * Cap what the session's caches may hold, in bytes.
 *
 * A host that knows its own limits should say. Android kills a process for
 * exceeding them and gives `onTrimMemory` no argument about the number.
 */
cb_status cb_config_set_cache_budget(struct cb_config *config, size_t bytes);

/**
 * Release a configuration that was never handed to a `cb_session_open_*`.
 * Passing null is a no-op.
 */
void cb_config_free(struct cb_config *config);

/**
 * Which edge the open book reads from.
 */
cb_status cb_session_reading_direction(const struct cb_session *session,
                                       cb_reading_direction *direction);

/**
 * Reconfigure the tap bands: how wide the previous- and next-page bands
 * are, as fractions of the page width, and what a tap between them does —
 * `CB_ACTION_NONE` for a middle band that does nothing, which is what a
 * host running its own menu gesture wants. Until this is called, a
 * session has the default policy: thirds, with the middle
 * `CB_ACTION_TOGGLE_MENU`.
 *
 * The reading direction is deliberately not a parameter. It is the
 * book's, and is re-read here, so a host cannot flip a book by
 * configuring it. Bands overlapping resolve to the previous-page side;
 * a zero-width band is disabled, and its space goes to the middle.
 */
cb_status cb_session_set_tap_zones(struct cb_session *session,
                                   float prev_fraction,
                                   float next_fraction,
                                   cb_action middle);

/**
 * What a tap at a point means, or `CB_ACTION_NONE` for nothing.
 *
 * `x` and `y` are **logical units** in **panel** coordinates — the
 * numbers a touch event actually carries, in the same space
 * `cb_session_set_metrics` was given. On iOS a `UITouch` location is
 * already logical: pass it as is. On Android a `MotionEvent` is in view
 * pixels: divide by density first, or every tap on a dense screen lands
 * in the last band and nothing errors. A rotated panel is undone on this
 * side, so a host never applies the inverse itself.
 *
 * The bands were resolved against the book's reading direction when they
 * were configured, which is why the answer is the session's to give:
 * the same tap on the same box means previous-page in an English book
 * and next-page in a Hebrew one.
 *
 * `CB_ERR_UNAVAILABLE` until metrics are set — a session with no page
 * box cannot say where its thirds are.
 */
cb_status cb_session_tap_action(const struct cb_session *session,
                                float x,
                                float y,
                                cb_action *action);

/**
 * What a key does in the default table, or `CB_ACTION_NONE` for one this
 * reader does not bind — in which case the host should handle the press
 * itself rather than swallow it.
 *
 * Free of any session, because the value is the default table itself: it
 * already knows the bezel buttons on a Kobo and the volume keys an
 * Android reader borrows, which is the difference between porting a
 * shell and reverse-engineering one. A host that lets readers rebind
 * keys keeps its overrides on its own side and falls back to this.
 *
 * Arrow keys are bound *logically* — `CB_KEY_ARROW_RIGHT` is the next
 * page in both reading directions — which at least agrees with what the
 * tap zones resolve to.
 */
cb_action cb_key_default_action(cb_key key);

/**
 * What a printable character does in the default table, or
 * `CB_ACTION_NONE`. The other half of [`cb_key_default_action`], split
 * out because a character is a Unicode scalar and not a member of a
 * closed set.
 *
 * `codepoint` is a Unicode scalar value. The table binds lowercase
 * letters; ASCII uppercase is folded here so a host need not care, and
 * anything that is not a scalar value answers `CB_ACTION_NONE`.
 * Unmodified presses only, as above.
 */
cb_action cb_char_default_action(uint32_t codepoint);

/**
 * Apply a reader intent, and learn both of the things a host needs to
 * know about what happened — see [`cb_action_outcome`].
 *
 * `CB_ACTION_NONE` is refused as `CB_ERR_INVALID_ARGUMENT` rather than
 * treated as a quiet no-op: a host holding `NONE` has a tap or a key
 * that meant nothing, and applying it anyway is a bug worth hearing
 * about on the spot.
 */
cb_status cb_session_apply(struct cb_session *session,
                           cb_action action,
                           cb_action_outcome *outcome);

/**
 * Send the engine's diagnostics to `callback` at `max_level` and above.
 *
 * Pass a null `callback` to stop delivery; the ABI keeps working and goes
 * quiet. `user` is stored and handed back untouched, and must stay valid
 * until the callback is replaced or cleared.
 *
 * Call it before opening anything — the failures most worth seeing are the
 * ones during `cb_session_open_*`.
 *
 * Only one sink exists per process, because `log` allows one logger per
 * process. Calling this again replaces it rather than adding a second.
 * Nothing is logged per frame or per page turn, so this is not on a hot
 * path.
 */
cb_status cb_set_log_callback(cb_log_fn callback, void *user, cb_log_level max_level);

/**
 * Emit a diagnostic through whatever sink is installed.
 *
 * Here so a host can put its own messages in the same stream as the
 * engine's, in the same order, without maintaining a second path — which
 * is the whole reason interleaved logs are worth having. `target` may be
 * null, and defaults to `host`.
 */
cb_status cb_log(cb_log_level level, const char *target, const char *message);

/**
 * Whether a sink is installed. Cheap; for a host deciding whether to
 * bother formatting something expensive.
 */
bool cb_log_enabled(void);

/**
 * Open a book from a filesystem path. **Consumes `config`** either way.
 *
 * Returns null on failure; `cb_last_error_message` says why. Only path
 * sources reach the library, so this is the one door with a reading
 * position behind it.
 */
struct cb_session *cb_session_open_path(const char *path, struct cb_config *config);

/**
 * Open a book from bytes the host already holds — a WASM `ArrayBuffer`, a
 * download it performed itself. The bytes are copied; the caller's buffer
 * is its own again on return.
 *
 * **Consumes `config`.** Does not reach the library: there is no file to
 * fingerprint, so the book opens at the beginning every time.
 */
struct cb_session *cb_session_open_bytes(const uint8_t *bytes,
                                         size_t len,
                                         cb_format format,
                                         struct cb_config *config);

/**
 * Open a book from an already-open file descriptor — an Android
 * `content://` URI resolved through `ParcelFileDescriptor`, an iOS
 * security-scoped file.
 *
 * **Takes ownership of `fd`** and closes it when the session is closed, so
 * the caller must have detached it. **Consumes `config`.** Does not reach
 * the library, for the same reason as bytes.
 *
 * Unix only: a descriptor is what Android and iOS hand out, and Windows
 * has no analogue worth guessing at from here.
 */
struct cb_session *cb_session_open_fd(int32_t fd, cb_format format, struct cb_config *config);

/**
 * Close a session and release everything it holds. Passing null is a
 * no-op. Every handle from a `cb_session_open_*` must reach this exactly
 * once.
 */
void cb_session_close(struct cb_session *session);

/**
 * The message behind the last failure **on this thread**, as a
 * NUL-terminated string.
 *
 * Call with `cap` 0 and `buf` null to learn the size, then again with a
 * buffer. Empty when nothing has failed. **The text is not stable** — it
 * is for logs and bug reports; branch on the status code instead.
 */
cb_status cb_last_error_message(char *buf, size_t cap, size_t *needed);

/**
 * Give the session its page box. Required before anything paginates: a
 * session with no metrics has no pages, and reports `CB_ERR_UNAVAILABLE`
 * when asked for a size or a render.
 */
cb_status cb_session_set_metrics(struct cb_session *session, struct cb_metrics metrics);

/**
 * Turn forward one page, crossing into the next unit at the end of this
 * one. `*moved` reports whether the position changed.
 *
 * **Use `*moved`.** Do not compare positions across a turn: that is the
 * defect this out-parameter exists to prevent.
 */
cb_status cb_session_next_page(struct cb_session *session, bool *moved);

/**
 * Turn back one page. `*moved` reports whether the position changed.
 */
cb_status cb_session_prev_page(struct cb_session *session, bool *moved);

/**
 * Skip to the start of the next unit. `*moved` reports whether it moved.
 */
cb_status cb_session_next_unit(struct cb_session *session, bool *moved);

/**
 * Skip to the start of the previous unit. `*moved` reports whether it moved.
 */
cb_status cb_session_prev_unit(struct cb_session *session, bool *moved);

/**
 * Where the reader is, as the pair.
 */
cb_status cb_session_position(const struct cb_session *session, struct cb_position *position);

/**
 * How many units the spine holds. Never compacted: a dangling idref keeps
 * its slot, because indices are locator identity.
 */
cb_status cb_session_spine_len(const struct cb_session *session, size_t *len);

/**
 * How many pages the current unit holds at the current metrics. Lays the
 * unit out if it has not been laid out yet, so it is not free.
 */
cb_status cb_session_page_count(struct cb_session *session, size_t *count);

/**
 * The book's title. Caller-allocates; see [`cb_last_error_message`] for
 * the two-call idiom.
 */
cb_status cb_session_title(const struct cb_session *session, char *buf, size_t cap, size_t *needed);

/**
 * Whether the open book pages as text or as images.
 */
cb_status cb_session_book_kind(const struct cb_session *session, cb_book_kind *kind);

/**
 * The settings in force for the open book.
 */
cb_status cb_session_settings(const struct cb_session *session, struct cb_settings *settings);

/**
 * Apply settings, keeping the reader's place across the reflow.
 */
cb_status cb_session_set_settings(struct cb_session *session,
                                  struct cb_settings settings,
                                  cb_settings_scope scope);

/**
 * The device-pixel size a surface must be for [`cb_session_render_into`],
 * rotation included.
 *
 * A host cannot allocate a surface without this, and must not compute it
 * itself: the logical-to-device round trip does not always land on the
 * pixel it started from, and `cb_session_render_into` refuses a
 * mismatched buffer rather than misdrawing into it.
 *
 * `CB_ERR_UNAVAILABLE` until metrics are set.
 */
cb_status cb_session_render_size(const struct cb_session *session,
                                 uint32_t *width,
                                 uint32_t *height);

/**
 * Rasterize the current page into a buffer the caller owns.
 *
 * `width` and `height` must equal [`cb_session_render_size`]; `stride` is
 * the byte distance between rows and must be at least `width * 4`. Pixels
 * come back **premultiplied RGBA8888**, which is what Android's
 * `ARGB_8888` holds natively, so the common path converts nothing.
 *
 * An unrotated page whose stride is exactly `width * 4` is rasterized
 * straight into `dst` with no intermediate and no copy. A rotated page or
 * a padded stride goes through a temporary and is copied row by row —
 * correct either way, free only in the first case, and every named
 * platform hits the first case.
 *
 * A surface whose dimensions disagree with `cb_session_render_size`, a
 * stride narrower than a row, or a buffer too short for the two, are all
 * `CB_ERR_INVALID_ARGUMENT` and nothing is written. `CB_ERR_UNAVAILABLE`
 * means the size was right and there is simply nothing to draw yet.
 */
cb_status cb_session_render_into(struct cb_session *session,
                                 uint8_t *dst,
                                 size_t len,
                                 uint32_t width,
                                 uint32_t height,
                                 size_t stride);

/**
 * Save the reading position and let go of everything reconstructible.
 *
 * Call it from the last callback the platform guarantees — Android's
 * `onStop`, iOS's `willResignActive`. The session stays usable; the
 * library reopens by itself if something needs it.
 */
cb_status cb_session_suspend(struct cb_session *session);

/**
 * Drop cached layouts and decoded images. The current page is rebuilt on
 * the next render. For Android's `onTrimMemory` and iOS's memory warning.
 */
cb_status cb_session_release_caches(struct cb_session *session);

/**
 * Bytes the caches currently hold.
 */
cb_status cb_session_cache_bytes(const struct cb_session *session, size_t *bytes);

/**
 * The ceiling those bytes are held under.
 */
cb_status cb_session_cache_budget(const struct cb_session *session, size_t *bytes);

/**
 * How many faces the font source actually produced.
 *
 * Worth showing once at startup. Zero never reaches a host — a source that
 * resolves to nothing fails the open with `CB_ERR_FONT` — but the number
 * still distinguishes a device that found its system fonts from one
 * running on a single embedded face.
 */
cb_status cb_session_font_face_count(const struct cb_session *session, size_t *count);

/**
 * Generic families that resolved to a name no loaded face carries, as
 * `generic=family`, one per line. Empty when everything resolved.
 *
 * Not an error: a book that never asks for `cursive` never notices. It is
 * the difference between a device a developer can diagnose and one they
 * have to guess at.
 */
cb_status cb_session_font_unresolved(const struct cb_session *session,
                                     char *buf,
                                     size_t cap,
                                     size_t *needed);

/**
 * Install the wake callback. `user` is handed back untouched.
 *
 * The pointer must stay valid until the session is closed or the waker is
 * replaced, and the callback may run on any thread.
 */
cb_status cb_session_set_waker(struct cb_session *session, cb_wake_fn wake, void *user);

/**
 * Take delivery of anything the loader finished. `*changed` reports
 * whether the visible page is now different, and therefore whether a
 * repaint is worth doing.
 */
cb_status cb_session_poll_loaded(struct cb_session *session, bool *changed);

/**
 * Whether any unit is still being loaded. A host that wants to show a
 * spinner asks this; one that just repaints on wake does not need it.
 */
cb_status cb_session_has_pending_loads(const struct cb_session *session, bool *pending);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CHAPBOOK_H */
