[package]
name = "chapbook-viewer-gtk"
description = "GTK4 reference viewer for chapbook"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
chapbook-core = { workspace = true }
chapbook-reader = { workspace = true, features = ["cbz", "pdf", "opds"] }
chapbook-render-tinyskia = { workspace = true }
gtk4 = { version = "0.11", features = ["v4_10"] }
